### PR TITLE
Allow nullableliteral in type application

### PR DESCRIPTION
**Pull request by teppeis**
Fix unexpected token error for `Array<?>`

### CODE REVIEW

**Comment by Constellation** [comment]
LGTM

**Comment by Constellation** [comment]
OK, test passed. Merging.

**Comment by Constellation** [comment]
Thx!

**Comment by teppeis** [comment]
thanks!

**Comment by Constellation** [comment]
Published as `0.6.3` :)

**Comment by Constellation** [comment]
Oops, fixed some bugs (in my code) and released it as `0.6.4`.

**Pull request merged**
